[build]
  command = "npm run build:verbose"
  publish = "dist"

[build.environment]
  NODE_VERSION = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
